### ISSUE TITLE
Problems with the download of some tables

### ISSUE THREAD

**Issue by xburj** [petrbouchal/czso#52]
There is error message, when downloading some tables from the database. Most are coorect, but for example industrial output download has this problem (you can seee below).

> catalogue <- czso::czso_get_catalogue()
                                                                                      
> catalogue %>% 
+   filter(str_detect(title, "[Pp]růmysl")) %>% 
+   select(dataset_id, title, description)
# A tibble: 1 × 3
  dataset_id title                     description                                      
  <chr>      <chr>                     <chr>                                            
1 150196     Index průmyslové produkce Datová sada obsahuje časovou řadu s údaji o vývo…
> # Dataset download
> prumysl <- czso_get_table("150196")
Error: lexical error: invalid character inside string.
          418/198519054/150196-23dds.htm ","temporal_start":"2000-01-0
                     (right here) ------^

**Comment by petrbouchal** [comment]
Thanks for catching this. This seems to be a problem on the provider side - there are newlines inside JSON, which makes the output of the API invalid.

I put in a temporary fix - please install via `r remotes::install_github('petrbouchal/czso')` and will also report to the provider.

I think the issue is resolved for now - feel free to reopen if you still encounter it.

**Comment by petrbouchal** [comment]
This is now fixed upstream by the data provider, so the CRAN version should work again.

**Comment by xburj** [comment]
Thanks a lot for fixing
